# Generated by Django 3.1.7 on 2022-01-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_list_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='num_of_tasks',
        ),
    ]
