# Generated by Django 3.1.7 on 2022-01-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_remove_list_num_of_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
